In [1]:
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A

NameError: name 'loss_log' is not defined

<Figure size 720x576 with 0 Axes>

In [4]:
from PIL import Image
import numpy as np
import sys
import os
import csv


def createFileList(myDir, format='.jpg'):
    fileList = []
    print(myDir)
    for root, dirs, files in os.walk(myDir, topdown=False):
        for name in files:
            if name.endswith(format):
                fullName = os.path.join(root, name)
                fileList.append(fullName)
    return fileList
# load the original image
myFileList = createFileList('/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A')
for file in myFileList:
    print(file)
    img_file = Image.open(file)

    # get original image parameters...
    width, height = img_file.size
    format = img_file.format
    mode = img_file.mode

     # Make image Greyscale
    img_grey = img_file.convert('L')
    value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))


    value = value.flatten()
    print(value)
    with open("img_pixels.csv", 'a') as f:
        writer = csv.writer(f)
        writer.writerow(value)

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A25.jpg
[34 31 29 ... 29 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2286.jpg
[31 30 31 ... 29 27 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1957.jpg
[29 34 29 ... 28 27 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A618.jpg
[33 30 30 ... 31 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1943.jpg
[34 33 29 ... 27 32 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A31.jpg
[34 29 31 ... 30 30 29]


<ipython-input-4-5b7487173982>:30: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))


/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2292.jpg
[34 31 32 ... 28 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A142.jpg
[33 31 30 ... 28 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A19.jpg
[35 32 29 ... 29 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A624.jpg
[35 30 30 ... 29 31 28]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A630.jpg
[35 31 30 ... 30 30 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A156.jpg
[37 32 30 ... 28 30 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1994.jpg
[32 31 29 ... 29 29 31]
/Users/jackgaither/desktop/capstone2/project/tr

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1360.jpg
[32 32 30 ... 28 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A591.jpg
[32 29 32 ... 28 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1406.jpg
[29 31 29 ... 28 29 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1412.jpg
[30 33 29 ... 26 32 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1374.jpg
[30 32 29 ... 28 28 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A585.jpg
[36 31 30 ... 29 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1823.jpg
[36 32 30 ... 28 29 31]
/Users/jackgaither/desktop/capstone2/projec

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2654.jpg
[32 29 29 ... 30 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2132.jpg
[36 30 31 ... 29 28 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A221.jpg
[34 29 30 ... 31 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A547.jpg
[35 32 30 ... 31 29 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2867.jpg
[32 31 29 ... 29 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2873.jpg
[29 30 29 ... 31 26 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A553.jpg
[37 32 29 ... 29 29 30]
/Users/jackgaither/desktop/capstone2/project

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1798.jpg
[33 34 29 ... 28 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A169.jpg
[34 29 31 ... 30 30 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1940.jpg
[33 32 29 ... 26 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A32.jpg
[37 31 30 ... 28 31 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2291.jpg
[35 30 30 ... 28 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A26.jpg
[36 33 30 ... 29 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2285.jpg
[35 32 31 ... 28 25 31]
/Users/jackgaither/desktop/capstone2/project/t

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A551.jpg
[33 30 30 ... 29 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2871.jpg
[32 31 29 ... 30 27 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2642.jpg
[33 29 30 ... 29 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2124.jpg
[34 29 31 ... 27 27 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2130.jpg
[34 30 30 ... 29 28 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1439.jpg
[33 34 28 ... 28 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2656.jpg
[31 31 29 ... 30 27 31]
/Users/jackgaither/desktop/capstone2/proje

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A587.jpg
[35 31 30 ... 29 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1376.jpg
[29 32 30 ... 26 33 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1410.jpg
[30 33 30 ... 29 30 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2119.jpg
[32 29 31 ... 30 27 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1438.jpg
[33 33 29 ... 29 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2131.jpg
[31 30 32 ... 30 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2657.jpg
[33 31 30 ... 29 29 31]
/Users/jackgaither/desktop/capstone2/proje

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2.jpg
[36 30 31 ... 29 30 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A632.jpg
[33 31 30 ... 28 31 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1955.jpg
[31 32 29 ... 27 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2284.jpg
[34 29 31 ... 29 27 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A27.jpg
[36 30 31 ... 28 31 28]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2290.jpg
[34 29 31 ... 29 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A33.jpg
[34 29 32 ... 30 29 28]
/Users/jackgaither/desktop/capstone2/project/trai

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2041.jpg
[32 29 31 ... 31 26 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1548.jpg
[34 34 29 ... 28 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A226.jpg
[36 33 29 ... 31 26 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2860.jpg
[30 31 30 ... 29 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A540.jpg
[36 31 31 ... 30 28 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A554.jpg
[37 33 31 ... 29 30 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2874.jpg
[33 30 30 ... 31 26 31]
/Users/jackgaither/desktop/capstone2/project

[30 29 32 ... 30 26 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A3000.jpg
[30 29 29 ... 31 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1617.jpg
[30 29 29 ... 27 31 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1824.jpg
[34 30 30 ... 27 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2493.jpg
[32 30 30 ... 29 25 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2487.jpg
[32 29 32 ... 30 27 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1830.jpg
[31 32 29 ... 29 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1818.jpg
[35 31 30 ... 25 31 31]
/Users/jackgaithe

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A810.jpg
[32 32 30 ... 31 27 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1987.jpg
[33 33 29 ... 28 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2256.jpg
[35 33 30 ... 28 29 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1777.jpg
[31 33 29 ... 28 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A186.jpg
[32 29 31 ... 29 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2518.jpg
[32 29 31 ... 30 28 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A838.jpg
[30 30 30 ... 28 28 30]
/Users/jackgaither/desktop/capstone2/project

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2081.jpg
[31 29 30 ... 30 27 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2095.jpg
[34 30 32 ... 30 26 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1577.jpg
[29 33 29 ... 27 29 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A386.jpg
[32 31 30 ... 30 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2718.jpg
[32 29 30 ... 29 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1211.jpg
[33 34 28 ... 28 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1205.jpg
[32 31 29 ... 27 28 31]
/Users/jackgaither/desktop/capstone2/proje

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A967.jpg
[36 30 31 ... 29 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A973.jpg
[37 32 29 ... 28 29 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2453.jpg
[33 29 30 ... 31 27 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2335.jpg
[33 33 29 ... 30 25 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1614.jpg
[31 32 29 ... 27 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1172.jpg
[31 30 29 ... 29 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A783.jpg
[33 30 30 ... 30 28 30]
/Users/jackgaither/desktop/capstone2/project

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A422.jpg
[34 30 31 ... 30 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1984.jpg
[30 32 29 ... 28 32 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2255.jpg
[33 31 31 ... 28 28 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2533.jpg
[31 29 30 ... 29 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A813.jpg
[32 32 30 ... 28 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A807.jpg
[31 30 30 ... 29 27 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2527.jpg
[30 29 30 ... 30 28 32]
/Users/jackgaither/desktop/capstone2/project

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A323.jpg
[35 29 31 ... 29 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2965.jpg
[31 30 30 ... 28 32 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A445.jpg
[33 31 31 ... 29 31 28]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A451.jpg
[36 31 30 ... 30 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2971.jpg
[32 31 30 ... 29 32 28]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A337.jpg
[36 31 30 ... 29 27 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2024.jpg
[33 29 31 ... 29 27 31]
/Users/jackgaither/desktop/capstone2/project/

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1672.jpg
[33 33 29 ... 30 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1114.jpg
[31 33 29 ... 26 32 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A929.jpg
[35 33 29 ... 30 27 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1100.jpg
[32 33 28 ... 29 30 28]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2409.jpg
[31 30 30 ... 30 27 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1666.jpg
[30 33 29 ... 27 32 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2347.jpg
[32 31 29 ... 30 27 29]
/Users/jackgaither/desktop/capstone2/proje

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2794.jpg
[32 31 29 ... 29 28 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2780.jpg
[33 31 29 ... 30 27 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2958.jpg
[31 31 29 ... 30 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A478.jpg
[34 29 31 ... 31 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1289.jpg
[31 32 29 ... 26 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1706.jpg
[30 29 31 ... 27 32 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2569.jpg
[33 30 32 ... 31 28 30]
/Users/jackgaither/desktop/capstone2/proje

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A687.jpg
[34 30 30 ... 29 29 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A308.jpg
[33 29 31 ... 29 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2796.jpg
[29 30 31 ... 29 27 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2782.jpg
[31 29 29 ... 30 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A334.jpg
[32 30 30 ... 31 28 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A452.jpg
[36 30 31 ... 29 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2972.jpg
[31 29 30 ... 28 34 28]
/Users/jackgaither/desktop/capstone2/project/

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1670.jpg
[34 34 30 ... 30 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1664.jpg
[31 34 29 ... 29 27 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1102.jpg
[33 34 29 ... 28 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1665.jpg
[30 33 29 ... 26 31 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1103.jpg
[31 31 29 ... 29 30 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1117.jpg
[32 34 29 ... 27 31 28]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1671.jpg
[33 34 29 ... 28 28 30]
/Users/jackgaither/desktop/capstone2/proj

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2973.jpg
[32 30 30 ... 30 33 28]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A453.jpg
[35 31 30 ... 29 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2783.jpg
[33 30 29 ... 29 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A309.jpg
[34 32 30 ... 30 27 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2797.jpg
[31 29 30 ... 30 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2218.jpg
[33 31 30 ... 30 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1711.jpg
[32 32 29 ... 29 29 31]
/Users/jackgaither/desktop/capstone2/projec

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A83.jpg
[36 29 31 ... 28 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1729.jpg
[31 31 30 ... 29 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A457.jpg
[37 31 31 ... 29 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2977.jpg
[31 31 29 ... 30 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A331.jpg
[35 33 29 ... 29 30 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A325.jpg
[35 32 29 ... 29 28 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2963.jpg
[32 29 30 ... 29 31 30]
/Users/jackgaither/desktop/capstone2/project/t

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A912.jpg
[36 32 29 ... 29 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2432.jpg
[32 29 30 ... 27 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2354.jpg
[33 31 30 ... 29 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1885.jpg
[32 33 29 ... 26 32 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2433.jpg
[32 29 31 ... 30 26 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A913.jpg
[33 31 29 ... 30 26 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1884.jpg
[32 32 29 ... 28 30 30]
/Users/jackgaither/desktop/capstone2/projec

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A324.jpg
[34 31 32 ... 30 27 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A442.jpg
[33 31 30 ... 30 30 28]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2962.jpg
[30 29 29 ... 29 28 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2976.jpg
[30 29 29 ... 28 34 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A456.jpg
[33 29 29 ... 27 33 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A330.jpg
[35 33 30 ... 29 31 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2547.jpg
[29 29 29 ... 31 29 30]
/Users/jackgaither/desktop/capstone2/project/

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2237.jpg
[34 32 30 ... 29 26 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A94.jpg
[34 29 32 ... 30 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2960.jpg
[29 29 31 ... 30 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A440.jpg
[38 32 30 ... 29 29 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A326.jpg
[34 31 31 ... 30 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A332.jpg
[32 30 30 ... 29 29 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A454.jpg
[36 30 31 ... 29 29 29]
/Users/jackgaither/desktop/capstone2/project/tr

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A911.jpg
[33 31 29 ... 30 25 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1138.jpg
[29 30 31 ... 26 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2431.jpg
[31 29 31 ... 30 24 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2425.jpg
[34 32 31 ... 30 26 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A905.jpg
[34 30 29 ... 30 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1892.jpg
[30 30 30 ... 27 32 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2343.jpg
[33 29 30 ... 29 28 28]
/Users/jackgaither/desktop/capstone2/projec

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1515.jpg
[33 32 29 ... 27 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A469.jpg
[34 31 31 ... 31 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1298.jpg
[30 30 31 ... 28 30 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2791.jpg
[29 29 29 ... 29 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2949.jpg
[30 30 29 ... 30 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2785.jpg
[33 30 29 ... 29 28 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A333.jpg
[32 30 30 ... 28 27 30]
/Users/jackgaither/desktop/capstone2/projec

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1054.jpg
[34 31 30 ... 28 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A98.jpg
[36 30 30 ... 30 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1732.jpg
[31 33 29 ... 29 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1726.jpg
[33 32 29 ... 29 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2549.jpg
[31 31 29 ... 30 28 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1040.jpg
[29 32 30 ... 26 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A869.jpg
[31 30 30 ... 30 26 30]
/Users/jackgaither/desktop/capstone2/project

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A921.jpg
[32 32 29 ... 29 27 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1108.jpg
[30 32 28 ... 26 31 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2401.jpg
[35 31 31 ... 28 28 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1120.jpg
[32 31 28 ... 26 32 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A909.jpg
[34 32 29 ... 30 26 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2429.jpg
[34 29 30 ... 32 25 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1646.jpg
[29 32 29 ... 26 31 30]
/Users/jackgaither/desktop/capstone2/projec

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2762.jpg
[30 30 30 ... 28 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A471.jpg
[35 33 29 ... 31 29 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1280.jpg
[31 33 29 ... 29 30 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2789.jpg
[33 29 30 ... 32 27 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2951.jpg
[30 30 31 ... 29 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A317.jpg
[35 30 31 ... 28 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A303.jpg
[32 31 31 ... 29 29 30]
/Users/jackgaither/desktop/capstone2/project

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1043.jpg
[30 32 28 ... 27 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1725.jpg
[32 31 29 ... 26 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2238.jpg
[34 30 31 ... 28 29 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1731.jpg
[32 31 29 ... 28 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1057.jpg
[31 32 28 ... 26 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A329.jpg
[32 31 29 ... 28 27 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A315.jpg
[36 31 29 ... 30 30 30]
/Users/jackgaither/desktop/capstone2/projec

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1889.jpg
[32 33 30 ... 28 29 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2358.jpg
[31 29 31 ... 31 25 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1645.jpg
[29 32 29 ... 27 27 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1123.jpg
[31 32 29 ... 26 32 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1644.jpg
[34 32 29 ... 26 31 28]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1122.jpg
[30 30 29 ... 27 31 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1136.jpg
[36 35 28 ... 30 30 30]
/Users/jackgaither/desktop/capstone2/proj

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1283.jpg
[35 33 29 ... 30 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2952.jpg
[29 32 30 ... 29 31 28]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A328.jpg
[36 32 31 ... 30 28 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1730.jpg
[33 29 29 ... 27 32 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2239.jpg
[28 31 31 ... 28 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1056.jpg
[31 33 29 ... 28 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1042.jpg
[33 32 30 ... 28 28 31]
/Users/jackgaither/desktop/capstone2/proje

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A462.jpg
[33 29 32 ... 29 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2942.jpg
[31 30 30 ... 28 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A338.jpg
[37 32 29 ... 27 30 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1244.jpg
[34 34 29 ... 29 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2995.jpg
[31 29 29 ... 26 33 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1522.jpg
[33 31 32 ... 28 30 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1536.jpg
[32 33 29 ... 30 30 30]
/Users/jackgaither/desktop/capstone2/projec

[35 30 30 ... 29 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1127.jpg
[33 31 31 ... 26 32 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1899.jpg
[33 31 29 ... 29 29 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1641.jpg
[31 32 31 ... 27 33 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2348.jpg
[31 29 31 ... 30 25 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1655.jpg
[33 32 29 ... 28 32 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1133.jpg
[32 33 29 ... 28 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A729.jpg
[34 30 31 ... 30 31 31]
/Users/jackgaither

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1053.jpg
[32 32 29 ... 26 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1735.jpg
[32 33 29 ... 26 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2228.jpg
[32 29 31 ... 28 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1721.jpg
[32 32 30 ... 28 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1047.jpg
[32 33 29 ... 31 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A885.jpg
[35 32 30 ... 29 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1912.jpg
[30 34 28 ... 26 31 30]
/Users/jackgaither/desktop/capstone2/proje

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2028.jpg
[34 30 31 ... 28 28 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1521.jpg
[30 30 29 ... 26 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1247.jpg
[33 34 28 ... 27 32 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2996.jpg
[31 29 31 ... 27 32 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2766.jpg
[29 29 29 ... 29 29 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2000.jpg
[31 31 30 ... 27 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1509.jpg
[34 32 29 ... 26 32 30]
/Users/jackgaither/desktop/capstone2/proj

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1124.jpg
[32 32 29 ... 31 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1871.jpg
[32 31 29 ... 29 30 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1865.jpg
[35 29 32 ... 27 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A702.jpg
[34 31 30 ... 29 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1695.jpg
[34 33 30 ... 26 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2388.jpg
[31 31 29 ... 29 27 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1681.jpg
[32 32 31 ... 28 30 30]
/Users/jackgaither/desktop/capstone2/proje

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1722.jpg
[29 31 29 ... 27 28 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1736.jpg
[31 34 30 ... 27 31 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2559.jpg
[32 32 29 ... 30 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A879.jpg
[33 30 30 ... 30 26 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1050.jpg
[29 32 30 ... 27 29 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A892.jpg
[33 31 29 ... 30 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A77.jpg
[33 30 31 ... 29 31 28]
/Users/jackgaither/desktop/capstone2/project/

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1547.jpg
[29 30 29 ... 28 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2728.jpg
[30 29 30 ... 29 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1221.jpg
[31 31 29 ... 26 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A229.jpg
[35 31 30 ... 31 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2853.jpg
[31 29 30 ... 29 28 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A573.jpg
[33 29 31 ... 29 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1382.jpg
[32 31 30 ... 26 29 30]
/Users/jackgaither/desktop/capstone2/projec

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1181.jpg
[31 33 29 ... 28 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A758.jpg
[36 31 30 ... 29 30 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A980.jpg
[35 31 29 ... 28 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1817.jpg
[30 35 28 ... 28 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1803.jpg
[31 30 30 ... 27 28 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A994.jpg
[33 31 31 ... 26 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1432.jpg
[34 33 29 ... 27 28 30]
/Users/jackgaither/desktop/capstone2/project

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A176.jpg
[34 31 30 ... 28 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1787.jpg
[33 30 29 ... 26 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A162.jpg
[35 30 30 ... 30 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1793.jpg
[34 33 29 ... 28 28 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A39.jpg
[34 29 31 ... 28 30 28]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A604.jpg
[35 31 30 ... 29 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1963.jpg
[32 33 29 ... 28 29 30]
/Users/jackgaither/desktop/capstone2/project/t

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A216.jpg
[33 29 30 ... 27 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2688.jpg
[32 30 29 ... 30 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2850.jpg
[30 30 29 ... 31 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A570.jpg
[34 29 31 ... 29 28 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1381.jpg
[32 33 29 ... 26 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2663.jpg
[31 31 30 ... 31 27 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2105.jpg
[33 30 32 ... 31 26 30]
/Users/jackgaither/desktop/capstone2/projec

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1425.jpg
[32 32 29 ... 29 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2892.jpg
[30 30 29 ... 30 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1343.jpg
[35 31 29 ... 28 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1357.jpg
[31 33 30 ... 29 28 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2886.jpg
[29 31 29 ... 29 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2138.jpg
[33 29 29 ... 30 26 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1431.jpg
[34 32 29 ... 26 30 31]
/Users/jackgaither/desktop/capstone2/proj

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1784.jpg
[32 33 28 ... 27 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A613.jpg
[36 31 30 ... 31 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1974.jpg
[32 33 29 ... 29 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1960.jpg
[32 32 29 ... 29 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A149.jpg
[33 30 31 ... 30 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A12.jpg
[34 29 31 ... 30 29 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A617.jpg
[36 32 29 ... 28 31 28]
/Users/jackgaither/desktop/capstone2/project/t

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1435.jpg
[30 35 30 ... 28 29 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2882.jpg
[30 29 29 ... 27 29 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1353.jpg
[33 34 29 ... 27 32 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1347.jpg
[34 33 29 ... 28 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2896.jpg
[29 29 30 ... 32 27 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2128.jpg
[33 29 31 ... 27 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1421.jpg
[29 33 30 ... 27 32 30]
/Users/jackgaither/desktop/capstone2/proj

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2897.jpg
[31 30 29 ... 31 26 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1346.jpg
[31 33 28 ... 30 26 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1420.jpg
[35 34 28 ... 26 30 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2129.jpg
[33 29 30 ... 30 28 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1434.jpg
[31 31 29 ... 28 29 32]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1352.jpg
[32 33 29 ... 26 29 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2883.jpg
[31 31 29 ... 30 27 32]
/Users/jackgaither/desktop/capstone2/proj

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1781.jpg
[30 32 31 ... 27 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A600.jpg
[36 31 30 ... 28 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1797.jpg
[35 32 29 ... 29 31 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A166.jpg
[35 32 29 ... 30 30 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1783.jpg
[32 33 29 ... 28 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A172.jpg
[35 30 30 ... 29 31 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A29.jpg
[34 30 29 ... 31 30 28]
/Users/jackgaither/desktop/capstone2/project/t

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2671.jpg
[33 30 29 ... 31 29 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1378.jpg
[32 33 29 ... 28 29 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A589.jpg
[35 31 31 ... 28 31 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2665.jpg
[30 31 29 ... 31 28 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2103.jpg
[33 30 31 ... 28 27 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1185.jpg
[33 31 31 ... 26 32 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A774.jpg
[33 29 32 ... 30 32 30]
/Users/jackgaither/desktop/capstone2/projec

/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A2843.jpg
[28 30 32 ... 31 27 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1392.jpg
[35 36 28 ... 28 30 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A563.jpg
[37 32 29 ... 29 30 30]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A205.jpg
[33 31 29 ... 28 31 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A211.jpg
[33 30 31 ... 29 28 31]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A1386.jpg
[32 31 29 ... 29 31 29]
/Users/jackgaither/desktop/capstone2/project/training_datasets/asl_alphabet_train/asl_alphabet_train/A/A577.jpg
[37 32 30 ... 29 30 28]
/Users/jackgaither/desktop/capstone2/project/